# coding: utf-8

"""
    Layered Insight Assessment, Compliance, Witness & Control

    LI Assessment & Compliance performs static vulnerability analysis, license and package compliance. LI Witness provides deep insight and analytics into containerized applications. Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.10
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ComplianceHistory(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'compliances': 'list[ComplianceHistoryCompliances]'
    }

    attribute_map = {
        'count': 'Count',
        'compliances': 'Compliances'
    }

    def __init__(self, count=None, compliances=None):
        """
        ComplianceHistory - a model defined in Swagger
        """

        self._count = None
        self._compliances = None

        if count is not None:
          self.count = count
        if compliances is not None:
          self.compliances = compliances

    @property
    def count(self):
        """
        Gets the count of this ComplianceHistory.

        :return: The count of this ComplianceHistory.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this ComplianceHistory.

        :param count: The count of this ComplianceHistory.
        :type: int
        """

        self._count = count

    @property
    def compliances(self):
        """
        Gets the compliances of this ComplianceHistory.

        :return: The compliances of this ComplianceHistory.
        :rtype: list[ComplianceHistoryCompliances]
        """
        return self._compliances

    @compliances.setter
    def compliances(self, compliances):
        """
        Sets the compliances of this ComplianceHistory.

        :param compliances: The compliances of this ComplianceHistory.
        :type: list[ComplianceHistoryCompliances]
        """

        self._compliances = compliances

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ComplianceHistory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
