# coding: utf-8

"""
    Layered Insight Assessment, Compliance, Witness & Control

    LI Assessment & Compliance performs static vulnerability analysis, license and package compliance. LI Witness provides deep insight and analytics into containerized applications. Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.10
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ComplianceHistoryCompliances(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'date': 'str',
        '_pass': 'int',
        'fail': 'int',
        'fail_compliance': 'list[ComplianceHistoryFailCompliance]'
    }

    attribute_map = {
        'date': 'Date',
        '_pass': 'Pass',
        'fail': 'Fail',
        'fail_compliance': 'FailCompliance'
    }

    def __init__(self, date=None, _pass=None, fail=None, fail_compliance=None):
        """
        ComplianceHistoryCompliances - a model defined in Swagger
        """

        self._date = None
        self.__pass = None
        self._fail = None
        self._fail_compliance = None

        if date is not None:
          self.date = date
        if _pass is not None:
          self._pass = _pass
        if fail is not None:
          self.fail = fail
        if fail_compliance is not None:
          self.fail_compliance = fail_compliance

    @property
    def date(self):
        """
        Gets the date of this ComplianceHistoryCompliances.

        :return: The date of this ComplianceHistoryCompliances.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """
        Sets the date of this ComplianceHistoryCompliances.

        :param date: The date of this ComplianceHistoryCompliances.
        :type: str
        """

        self._date = date

    @property
    def _pass(self):
        """
        Gets the _pass of this ComplianceHistoryCompliances.

        :return: The _pass of this ComplianceHistoryCompliances.
        :rtype: int
        """
        return self.__pass

    @_pass.setter
    def _pass(self, _pass):
        """
        Sets the _pass of this ComplianceHistoryCompliances.

        :param _pass: The _pass of this ComplianceHistoryCompliances.
        :type: int
        """

        self.__pass = _pass

    @property
    def fail(self):
        """
        Gets the fail of this ComplianceHistoryCompliances.

        :return: The fail of this ComplianceHistoryCompliances.
        :rtype: int
        """
        return self._fail

    @fail.setter
    def fail(self, fail):
        """
        Sets the fail of this ComplianceHistoryCompliances.

        :param fail: The fail of this ComplianceHistoryCompliances.
        :type: int
        """

        self._fail = fail

    @property
    def fail_compliance(self):
        """
        Gets the fail_compliance of this ComplianceHistoryCompliances.

        :return: The fail_compliance of this ComplianceHistoryCompliances.
        :rtype: list[ComplianceHistoryFailCompliance]
        """
        return self._fail_compliance

    @fail_compliance.setter
    def fail_compliance(self, fail_compliance):
        """
        Sets the fail_compliance of this ComplianceHistoryCompliances.

        :param fail_compliance: The fail_compliance of this ComplianceHistoryCompliances.
        :type: list[ComplianceHistoryFailCompliance]
        """

        self._fail_compliance = fail_compliance

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ComplianceHistoryCompliances):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
