# coding: utf-8

"""
    Layered Insight Assessment, Compliance, Witness & Control

    LI Assessment & Compliance performs static vulnerability analysis, license and package compliance. LI Witness provides deep insight and analytics into containerized applications. Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.10
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ContainerSystemcallMetricsItems(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'syscall': 'int',
        'data': 'list[int]'
    }

    attribute_map = {
        'syscall': 'Syscall',
        'data': 'Data'
    }

    def __init__(self, syscall=None, data=None):
        """
        ContainerSystemcallMetricsItems - a model defined in Swagger
        """

        self._syscall = None
        self._data = None

        if syscall is not None:
          self.syscall = syscall
        if data is not None:
          self.data = data

    @property
    def syscall(self):
        """
        Gets the syscall of this ContainerSystemcallMetricsItems.
        Number of system call

        :return: The syscall of this ContainerSystemcallMetricsItems.
        :rtype: int
        """
        return self._syscall

    @syscall.setter
    def syscall(self, syscall):
        """
        Sets the syscall of this ContainerSystemcallMetricsItems.
        Number of system call

        :param syscall: The syscall of this ContainerSystemcallMetricsItems.
        :type: int
        """

        self._syscall = syscall

    @property
    def data(self):
        """
        Gets the data of this ContainerSystemcallMetricsItems.
        System call amount and occurrence

        :return: The data of this ContainerSystemcallMetricsItems.
        :rtype: list[int]
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this ContainerSystemcallMetricsItems.
        System call amount and occurrence

        :param data: The data of this ContainerSystemcallMetricsItems.
        :type: list[int]
        """

        self._data = data

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ContainerSystemcallMetricsItems):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
