# coding: utf-8

"""
    Layered Insight Assessment, Compliance, Witness & Control

    LI Assessment & Compliance performs static vulnerability analysis, license and package compliance. LI Witness provides deep insight and analytics into containerized applications. Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.10
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class StatsHistoryInner(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'date': 'str',
        'vulnerabilites': 'list[StatsHistoryInnerVulnerabilites]'
    }

    attribute_map = {
        'date': 'Date',
        'vulnerabilites': 'Vulnerabilites'
    }

    def __init__(self, date=None, vulnerabilites=None):
        """
        StatsHistoryInner - a model defined in Swagger
        """

        self._date = None
        self._vulnerabilites = None

        if date is not None:
          self.date = date
        if vulnerabilites is not None:
          self.vulnerabilites = vulnerabilites

    @property
    def date(self):
        """
        Gets the date of this StatsHistoryInner.

        :return: The date of this StatsHistoryInner.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """
        Sets the date of this StatsHistoryInner.

        :param date: The date of this StatsHistoryInner.
        :type: str
        """

        self._date = date

    @property
    def vulnerabilites(self):
        """
        Gets the vulnerabilites of this StatsHistoryInner.

        :return: The vulnerabilites of this StatsHistoryInner.
        :rtype: list[StatsHistoryInnerVulnerabilites]
        """
        return self._vulnerabilites

    @vulnerabilites.setter
    def vulnerabilites(self, vulnerabilites):
        """
        Sets the vulnerabilites of this StatsHistoryInner.

        :param vulnerabilites: The vulnerabilites of this StatsHistoryInner.
        :type: list[StatsHistoryInnerVulnerabilites]
        """

        self._vulnerabilites = vulnerabilites

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, StatsHistoryInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
