# coding: utf-8

"""
    Layered Insight Assessment, Compliance, Witness & Control

    LI Assessment & Compliance performs static vulnerability analysis, license and package compliance. LI Witness provides deep insight and analytics into containerized applications. Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.10
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_api
from layint_api.rest import ApiException
from layint_api.apis.log_api import LogApi


class TestLogApi(unittest.TestCase):
    """ LogApi unit test stubs """

    def setUp(self):
        self.api = layint_api.apis.log_api.LogApi()

    def tearDown(self):
        pass

    def test_array_of_dropped_logs(self):
        """
        Test case for array_of_dropped_logs

        Get histograph of policy hits
        """
        pass

    def test_show_logs(self):
        """
        Test case for show_logs

        Get all logs
        """
        pass

    def test_show_logs_for_container(self):
        """
        Test case for show_logs_for_container

        Get container logs
        """
        pass


if __name__ == '__main__':
    unittest.main()
