# coding: utf-8

"""
    Layered Insight Assessment, Compliance, Witness & Control

    LI Assessment & Compliance performs static vulnerability analysis, license and package compliance. LI Witness provides deep insight and analytics into containerized applications. Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.10
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_api
from layint_api.rest import ApiException
from layint_api.apis.image_api import ImageApi


class TestImageApi(unittest.TestCase):
    """ ImageApi unit test stubs """

    def setUp(self):
        self.api = layint_api.apis.image_api.ImageApi()

    def tearDown(self):
        pass

    def test_add_image(self):
        """
        Test case for add_image

        Create new image definition
        """
        pass

    def test_assign_configuration_to_image(self):
        """
        Test case for assign_configuration_to_image

        Assign configuration to image
        """
        pass

    def test_assign_policy_to_image(self):
        """
        Test case for assign_policy_to_image

        Assign security policy to image
        """
        pass

    def test_delete_image(self):
        """
        Test case for delete_image

        Delete specified image
        """
        pass

    def test_get_agent_config(self):
        """
        Test case for get_agent_config

        Get the specified image configuration for the LI agent. The configuration consists of agent settings and policy rules.
        """
        pass

    def test_get_image(self):
        """
        Test case for get_image

        Get specified container image
        """
        pass

    def test_get_images(self):
        """
        Test case for get_images

        Get defined container images
        """
        pass

    def test_image_id_level_syscall_category_metrics(self):
        """
        Test case for image_id_level_syscall_category_metrics

        Get histograph information for system calls divided into category groups across all the containers which are using the image
        """
        pass

    def test_images_search_post(self):
        """
        Test case for images_search_post

        
        """
        pass

    def test_instrument_image(self):
        """
        Test case for instrument_image

        Request instrumentation of specified container image
        """
        pass

    def test_number_of_instrumented_images(self):
        """
        Test case for number_of_instrumented_images

        Returns number of instrumented images
        """
        pass

    def test_show_container_running_image(self):
        """
        Test case for show_container_running_image

        Get specified container image
        """
        pass

    def test_update_image(self):
        """
        Test case for update_image

        Update image definition
        """
        pass


if __name__ == '__main__':
    unittest.main()
