# coding: utf-8

"""
    Layered Insight Assessment, Compliance, Witness & Control

    LI Assessment & Compliance performs static vulnerability analysis, license and package compliance. LI Witness provides deep insight and analytics into containerized applications. Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.10
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_api
from layint_api.rest import ApiException
from layint_api.apis.analytics_api import AnalyticsApi


class TestAnalyticsApi(unittest.TestCase):
    """ AnalyticsApi unit test stubs """

    def setUp(self):
        self.api = layint_api.apis.analytics_api.AnalyticsApi()

    def tearDown(self):
        pass

    def test_cve_search(self):
        """
        Test case for cve_search

        Searches image scan results for specified CVE ID
        """
        pass

    def test_get_stats(self):
        """
        Test case for get_stats

        Gets vulnerability statistics for user's images
        """
        pass

    def test_package_search(self):
        """
        Test case for package_search

        Searches for images with a specified software package
        """
        pass

    def test_stats_history_get(self):
        """
        Test case for stats_history_get

        Get vulnerability history over a time period
        """
        pass

    def test_top_cves(self):
        """
        Test case for top_cves

        Returns a list of most common/severe vulnerabilities present in a users images
        """
        pass

    def test_top_vuln_images(self):
        """
        Test case for top_vuln_images

        Returns a list of most vulnerable images
        """
        pass


if __name__ == '__main__':
    unittest.main()
