# coding: utf-8

"""
    Layered Insight Assessment, Compliance, Witness & Control

    LI Assessment & Compliance performs static vulnerability analysis, license and package compliance. LI Witness provides deep insight and analytics into containerized applications. Control provides dynamic runtime security and analytics for containerized applications. You can find out more about the Layered Insight Suite at [http://layeredinsight.com](http://layeredinsight.com).

    OpenAPI spec version: 0.10
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_api
from layint_api.rest import ApiException
from layint_api.apis.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """ TagsApi unit test stubs """

    def setUp(self):
        self.api = layint_api.apis.tags_api.TagsApi()

    def tearDown(self):
        pass

    def test_add_tag(self):
        """
        Test case for add_tag

        Add a tag
        """
        pass

    def test_delete_tag(self):
        """
        Test case for delete_tag

        Delete a tag by ID
        """
        pass

    def test_get_tag(self):
        """
        Test case for get_tag

        Get a tag by ID
        """
        pass

    def test_get_tags(self):
        """
        Test case for get_tags

        List all tags
        """
        pass


if __name__ == '__main__':
    unittest.main()
